### ISSUE TITLE
Per category "show as free/busy" setting for outlook integration

### ISSUE THREAD

**Issue by javfg** [indico/indico-plugins-cern#128]
Request from [SNOW](https://cern.service-now.com/nav_to.do?uri=incident.do?sysparm_query=number=INC3415433).

Users claim it would be useful for them to be able to fine-grain the selection of the free/busy status depending on the category the event is from. Right now the setting is global (found in the user preferences).

**Comment by ThiefMaster** [comment]
OK, after some more feedback we'll add a setting to override it like this:

![image](https://github.com/indico/indico-plugins-cern/assets/179599/4e8311a4-7dd4-4fbe-bef1-e31a574b2876)


Maybe we'll add a nicer category picker at some point in the future; for now it will just be a text field to enter the category ID.
