### ISSUE TITLE
CERN Access: "personal data" reg. form section

### ISSUE THREAD

**Issue by pferreir** [indico/indico-plugins-cern#21]
Let's add a "personal data" section within the registration form (in events where CERN Access is active). Users who fill it in will be "accepted" by default.

**Comment by ThiefMaster** [comment]
Would it make sense to have some kind of "I need CERN site access" option below the normal form and only show the fields (as required fields) when someone selects that?

**Comment by pferreir** [comment]
Yes, that would be a great idea, I believe.

**Comment by ThiefMaster** [comment]
FYI, this should not be an actual regform section/field, but just be displayed after the form.

Backend-wise I guess the easiest option would be creating the access request with the `not_requested` state at registration time and then, when a manager requests site access, simply act differently depending on whether the user has already provided the data or not.
