### ISSUE TITLE
Move to new CERN Search system

### ISSUE THREAD

**Issue by pferreir** [indico/indico-plugins-cern#31]
Preliminary design document available [here](https://hackmd.web.cern.ch/XSJgr4M8SLqCIDvC5zC-Rg#).
The documentation of the new CERN Search system can be found [here](http://cernsearchdocs.web.cern.ch/cernsearchdocs/).

**Comment by mvidalgarcia** [comment]
Are we including the contribution minutes? I don't see any reference in the doc.

**Comment by ThiefMaster** [comment]
"notes" are minutes

**Comment by ThiefMaster** [comment]
this is done (citadel plugin in the main indico-plugins repo)
